reverse letters string 
<br>
reverse words string 
<br>
remove duplicates in array/string 
<br>
list of lists - flatten the list  
<br>
Python Object oriented - class inheritance, constructor call, child parent? multiple inheritance which values
# method resolution order in python
indexs - : -1 to reverse
<br>
list comprehensions

### 1.1 Is Unique

In [13]:
def is_unique(word):
    word = sorted(word)
    for i in range(len(word)-1):
        if word[i] == word[i+1]:
            return False
    return True

In [29]:
print is_unique('saisandeep')
print is_unique('ramsi')

False
True


In [22]:
def is_unique2(word):
    char_count = {}
    for letter in word:
        if letter in char_count.keys():
            return False
        char_count[letter] = 1
    return True
        

In [30]:
print is_unique2('saisandeep')
print is_unique2('ramsi')

False
True


### 1.2 Is Permutation

In [35]:
def is_permutation(a,b):
    a_dict = {}
    for letter in a:
        if letter in a_dict.keys():
            a_dict[letter] += 1
        a_dict[letter] = 1
    for letter in b:
        if letter in a_dict.keys():
            a_dict[letter] -= 1
        else:
            return False
    for i in a_dict.keys():
        if a_dict[i] != 0:
            return False
    return True

In [38]:
print is_permutation('ate','eat')
print is_permutation('saisand','ssandde')

True
False


### 1.3 URLify

replace spaces with 

In [3]:
def urlify(string, n):
    str_list = [str(x) for x in string]
    for i in range(n):
        if str_list[i] == ' ':
            str_list[i] = '%20'
    string = ''.join(str_list)
    return string
        

In [4]:
urlify('asbc asm as fs',14)

'asbc%20asm%20as%20fs'

### 1.4 Palindrome Permutation

In [16]:
def palin_perm(string):
    char_count = {}
    string = string.lower()
    for char in string:
        if char in char_count.keys():
            char_count[char] += 1
        else:
            char_count[char] = 1
    unique_count = 0
    for key in char_count.keys():
        if key!=' ' and char_count[key]%2 != 0:
            unique_count += 1
        if unique_count > 1:
            return False
    return True

In [21]:
print ord('A')
print ord('a')

65
97


ASCII value of 'A' is 65 and 'a' is 97 if needed to convert uppercase letters into lower case programatically

In [22]:
palin_perm('tacT cao')

True

### 1.5 One (or zero) edit away 

In [28]:
def one_away(a,b):
    if a==b:
        return True
    
    a_list = [str(x) for x in a]
    b_list = [str(x) for x in b]
    
    if abs(len(a_list) - len(b_list)) == 1:
        if (a in b) or (b in a):
            return True
        else:
            return False
    
    if len(a_list) == len(b_list):
        count = 0
        for i in range(len(a_list)):
            if a_list[i] != b_list[i]:
                count += 1
        if count > 1:
            return False
        else:
            return True


In [29]:
print one_away('pale','bale')
print one_away('pale','ale')
print one_away('pale','bake')
print one_away('pales','pale')

True
True
False
True


### 1.6 String compression

In [48]:
def str_comp(a):
    output = []
    input_str = [x for x in a]
    count = 1
    for i in range(len(input_str)-1):
        if input_str[i] == input_str[i+1]:
            count += 1
        else:
            output.append(input_str[i])
            output.append(str(count))
            count = 1
            
    output.append(input_str[i+1])
    output.append(str(count))
    
    output = ''.join(output)
    return output

In [51]:
print str_comp('saisandeep')
print str_comp('abbabaaaaddddccewwweeee')

s1a1i1s1a1n1d1e2p1
a1b2a1b1a4d4c2e1w3e4


### 1.3 Rotate matrix

In [3]:
def rot_mat(matrix):
    n = len(matrix)
    for row in range(n//2):
        for column in range(row, n-row-1):
            temp = matrix[column][n-row-1]
            matrix[column][n-row-1] = matrix[row][column]
            matrix[row][column] = matrix[n-row-column-1][row]
            matrix[n-row-column-1][row] = matrix[n-row-1][n-row-column-1]
            matrix[n-row-1][n-row-column-1] = temp
    return matrix

import numpy as np

matrix = np.random.rand(4,4)

print matrix
print rot_mat(matrix)

[[ 0.78045899  0.04449698  0.54068366  0.79650441]
 [ 0.83474973  0.99623376  0.3772206   0.40619594]
 [ 0.78610333  0.00509598  0.74043499  0.34687236]
 [ 0.89138377  0.23239458  0.72301274  0.23744352]]
[[ 0.89138377  0.78610333  0.83474973  0.78045899]
 [ 0.23239458  0.00509598  0.99623376  0.04449698]
 [ 0.72301274  0.3772206   0.74043499  0.54068366]
 [ 0.23744352  0.34687236  0.40619594  0.79650441]]


### 1.8 Zero Matrix

In [8]:
def zero_mat(matrix):
    m = len(matrix[0])
    n = len(matrix)
    rows = set()
    columns = set()
    
    for i in range(m):
        for j in range(n):
            if matrix[i][j] == 0:
                rows.add(i)
                columns.add(j)

    for row in rows:
        for col in range(n):
            matrix[row][col] = 0
    
    for column in columns:
        for row in range(m):
            matrix[row][column] = 0
    
    return matrix

m = [[1 ,2 ,3 ,4 ],
     [5 ,6 ,7 ,8 ],
     [9 ,0 ,11,12],
     [13,14,15,16]]

zero_mat(m)

[[1, 0, 3, 4], [5, 0, 7, 8], [0, 0, 0, 0], [13, 0, 15, 16]]

### 1.9 String rotation

In [11]:
def isSubstring(s1,s2):
    if s1 in s2:
        return True
    elif s2 in s1:
        return True
    else:
        return False
    
def isRotation(s1,s2):
    temp = s2+s2
    return isSubstring(s1, temp)

In [12]:
isRotation('saisandeep','sandeepsai')

True

In [13]:
print 'sai'+'sandeep'

saisandeep
